version: "3.9"
services:
  web:
    build: .
    container_name: php-docker
    ports:
      - 8080:8080
    volumes:
      - .:/var/www/html
    command:
      - php
      - -S
      - 0.0.0.0:8080
      - -t
      - public/
